- name: Test RTSP stream
  block:
    - name: Install required Python packages
      pip:
        name:
          - requests
        state: present

    - name: Build RTSP server image
      docker_image:
        name: rtsp-mock
        source: build
        build:
          path: "{{ playbook_dir }}/../.."
          dockerfile: rtsp/docker/Dockerfile
        force_source: yes

    - name: Check if RTSP server is running
      wait_for:
        port: 8554
        timeout: 5
      register: rtsp_running
      ignore_errors: yes
      changed_when: false

    - name: Start RTSP server if not running
      docker_container:
        name: rtsp-mock
        image: rtsp-mock
        state: started
        ports:
          - "8554:8554"
          - "8888:8888"
        restart_policy: unless-stopped
      when: not rtsp_running is succeeded
      register: rtsp_started
      changed_when: rtsp_started is changed

    - name: Wait for RTSP server to be ready
      wait_for:
        port: 8554
        timeout: 30
      when: not rtsp_running is succeeded

    - name: Verify RTSP server is accessible
      uri:
        url: http://localhost:8888/stats
        method: GET
        status_code: 200
        timeout: 5
      register: rtsp_status
      retries: 3
      delay: 2
      until: rtsp_status is succeeded
      ignore_errors: yes

    - name: Show RTSP server status
      debug:
        msg: "RTSP server is running and accessible"
      when: rtsp_status.status == 200

    - name: Fail if RTSP server is not accessible
      fail:
        msg: "RTSP server is not accessible"
      when: rtsp_status.status != 200

    - name: Stop RTSP server if we started it
      docker_container:
        name: rtsp-mock
        state: stopped
      when: rtsp_started is defined and rtsp_started is changed
