- name: Test RTSP stream
  block:
    - name: Install system dependencies
      apt:
        name:
          - python3-opencv
          - python3-numpy
        state: present
        update_cache: yes

    - name: Install required Python packages
      pip:
        name:
          - opencv-python-headless
          - numpy
        state: present

    - name: Check if RTSP server is running
      uri:
        url: http://localhost:9997/v1/config/get
        method: GET
        status_code: 200
        timeout: 5
      register: rtsp_status
      retries: 3
      delay: 2
      until: rtsp_status is succeeded
      ignore_errors: yes

    - name: Test RTSP stream connection
      script: test_rtsp.py
      register: rtsp_test
      changed_when: false
      failed_when: false
      environment:
        PYTHONUNBUFFERED: 1

    - name: Show RTSP test result
      debug:
        var: rtsp_test.stdout_lines

    - name: Fail if RTSP test failed
      fail:
        msg: "RTSP test failed - could not connect to stream"
      when: rtsp_test.rc != 0
