- name: Test RTSP stream
  block:
    - name: Install required Python packages
      pip:
        name:
          - requests
          - docker
        state: present

    - name: Ensure Docker SDK is available
      pip:
        name: docker
        state: present

    - name: Check if RTSP server container exists
      docker_container_info:
        name: rtsp-mock
      register: rtsp_container
      ignore_errors: yes

    - name: Start RTSP server container with embedded config
      docker_container:
        name: rtsp-mock
        image: aler9/rtsp-simple-server:latest
        state: started
        ports:
          - "8554:8554"
          - "8888:8888"
        command: >-
          --rtsp-address :8554
          --http-address :8888
          --paths "test: source: publisher"
      when: not rtsp_container.container.State.Running | default(false)
      register: container_started

    - name: Wait for RTSP server to be ready
      wait_for:
        port: 8554
        timeout: 30
      when: not rtsp_container.container.State.Running | default(false)

    - name: Check if RTSP server is running
      wait_for:
        port: 8554
        timeout: 5
      register: rtsp_running
      ignore_errors: yes

    - name: Show test result
      debug:
        msg: "RTSP server is running on port 8554"
      when: rtsp_running is succeeded

    - name: Fail if RTSP server is not accessible
      fail:
        msg: "RTSP server is not accessible on port 8554"
      when: rtsp_running is not succeeded
