- name: Test RTSP stream
  block:
    - name: Install required Python packages with pip
      pip:
        name:
          - opencv-python-headless
          - numpy
        state: present

    - name: Check if RTSP server is running
      wait_for:
        port: 8554
        timeout: 5
      register: rtsp_running
      ignore_errors: yes
      changed_when: false

    - name: Start RTSP server if not running
      docker_container:
        name: rtsp-mock
        image: rtsp-mock
        state: started
        ports:
          - "8554:8554"
          - "8888:8888"
        restart_policy: unless-stopped
      when: not rtsp_running is succeeded
      register: rtsp_started
      changed_when: rtsp_started is changed

    - name: Wait for RTSP server to be ready
      wait_for:
        port: 8554
        timeout: 30
      when: not rtsp_running is succeeded

    - name: Test RTSP stream connection
      script: test_rtsp.py
      register: rtsp_test
      changed_when: false
      failed_when: false
      environment:
        PYTHONUNBUFFERED: 1

    - name: Show RTSP test result
      debug:
        var: rtsp_test.stdout_lines

    - name: Fail if RTSP test failed
      fail:
        msg: "RTSP test failed - could not connect to stream"
      when: rtsp_test.rc != 0

    - name: Stop RTSP server if we started it
      docker_container:
        name: rtsp-mock
        state: stopped
      when: rtsp_started is defined and rtsp_started is changed
